const SUSPICIOUS_PATTERNS = [
  /\u6769\u6ec5\u25bc/,
  /\u93c8\ue100\u6e74/,
  /\u9477\ue044\u59e9/,
  /锟/,
  /閿熸枻鎷/,
  /婢跺洣/,
  /厧鍤/,
  /厧鍙/,
  /閺堝秴濮/,
  /閸旂姴鐦/,
  /鐠併倛鐦/,
  /閻劍鍩/,
  /缁旑垰褰/,
  /闁板秶鐤/,
  /娑撹鐦/,
  /閺佸繑鍔/,
  /鐎靛棛鐖/,
  /閻楀牊婀/,
  /閺堫亞鐓/,
  /鏉堟挸鍤/,
  /缂佸牏/,
  /娴兼俺鐦/,
  /澶囦唤/,
  /瀵煎嚭/,
  /褰撳墠/,
  /鐗堟湰/,
  /鍙戠幇/,
  /鏂扮増/,
  /鏈€鏂/,
  /鏇存柊/,
  /涓嬭浇/,
  /牎楠/,
  /瀹夎/,
  /噸鍚/,
  /鍏煎/,
  /閫氫/,
  /鏅鸿/,
  /纭呭/,
  /瀵嗙爜/,
  /鍔犲瘑鎭/,
  /澶嶅埗/,
  /缁堢/,
  /閲嶈繛/,
  /浼氳瘽/,
  /\u6769\u6EDE\u7A0B/,
  /\u7F01\u5802\u27EC/,
  /\u7025\u714E\u568C/,
  /\u93C6\u67C6/,
  /(?:\u93C8\uE046\u7161\u95BF\u6B12\uE1E4|\u93C8\uE051\u715A\u95BF\u6B0F\uE1E4)/,
  /\u9363\u55D8/,
  /妯[\s\S]{0,3}瀷/,
  /璁[\s\S]{0,3}垝/,
  /姝[\s\S]{0,2}/,
  /宸叉壒/,
  /寰呯/,
  /鍙[\s\S]{0,4}/,
  /\?{3,}/,
  /(?:SSH|SFTP) \?\?/,
];

export function findSuspiciousLocalizationText(content = "") {
  return String(content || "")
    .split(/\r?\n/)
    .map((text, index) => ({ line: index + 1, text }))
    .filter(({ text }) => SUSPICIOUS_PATTERNS.some((pattern) => pattern.test(text)))
    .map(({ line, text }) => ({ line, text: text.trim() }));
}
