/**
 * default setting
 */

export default {
  hotkey: 'Control+2',
  sshReadyTimeout: 50000,
  scrollback: 3000,
  onStartSessions: [],
  fontSize: 16,
  fontFamily: 'Maple Mono, mono, courier-new, courier, monospace',
  execWindows: 'System32/WindowsPowerShell/v1.0/powershell.exe',
  execMac: 'zsh',
  execLinux: 'bash',
  execWindowsArgs: [],
  execMacArgs: [],
  execLinuxArgs: [],
  enableGlobalProxy: false,
  disableConnectionHistory: false,
  disableTransferHistory: false,
  terminalBackgroundImagePath: '',
  terminalBackgroundFilterOpacity: 1,
  terminalBackgroundFilterBlur: 0,
  terminalBackgroundFilterBrightness: 1,
  terminalBackgroundFilterGrayscale: 0,
  terminalBackgroundFilterContrast: 1,
  terminalBackgroundText: '',
  terminalBackgroundTextSize: 48,
  terminalBackgroundTextColor: '#ffffff',
  terminalBackgroundTextFontFamily: 'Maple Mono',
  rendererType: 'dom',
  terminalType: 'xterm-256color',
  keepaliveCountMax: 10,
  keyword2FA: 'verification code,otp,one-time,two-factor,2fa,totp,authenticator,duo,yubikey,security code,mfa,passcode',
  saveTerminalLogToFile: false,
  checkUpdateOnStart: true,
  cursorBlink: false,
  cursorStyle: 'block',
  useSystemTitleBar: false,
  opacity: 1,
  defaultEditor: '',
  terminalWordSeparator: './\\()"\'-:,.;<>~!@#$%^&*|+=[]{}`~ ?',
  confirmBeforeExit: false,
  initDefaultTabOnStart: true,
  screenReaderMode: false,
  autoRefreshWhenSwitchToSftp: false,
  addTimeStampToTermLog: false,
  sftpPathFollowSsh: false,
  keepaliveInterval: 10000,
  backspaceMode: '^?',
  shiftEnterMode: '\\n',
  showHiddenFilesOnSftpStart: true,
  terminalInfos: [
    'uptime',
    'cpu',
    'mem',
    'activities',
    'network',
    'disks'
  ],
  filePropsEnabled: [
    'name',
    'size',
    'modifyTime'
  ],
  hideIP: false,
  dataSyncSelected: 'all',
  language: 'zh_cn',
  languageAI: '简体中文',
  nameAI: '',
  baseURLAI: 'https://api.atlascloud.ai/v1',
  modelAI: 'deepseek-chat',
  roleAI: 'SSH 运维专家，优先排查服务器、网络、日志、进程、端口、磁盘、内存、Nginx、Docker 和部署问题。回答使用中文和 Markdown。',
  apiPathAI: '',
  proxyAI: '',
  sessionLogPath: '',
  sshSftpSplitView: false,
  showCmdSuggestions: false,
  autoReconnectTerminal: false,
  startDirectoryLocal: '',
  allowMultiInstance: false,
  disableDeveloperTool: false,
  dragDropBehavior: 'ask'
}
